printWidth = 90
semi = false
singleQuote = false
quoteProps = "preserve"
trailingComma = "none"
bracketSpacing = true
arrowParens = "avoid"
proseWrap = "always"
# let git handle normalizing
endOfLine = "auto"
